---
- name: Create a new azure instance
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars_files: 'vaults/sqlvault.yml'
  
  tasks:
  - name: Create New Instance
    azure_rm_virtualmachine:
      name: "{{ item.name }}"
      resource_group: "{{ item.rg }}"
      vm_size: "{{ item.vm_size | default('Standard_B1ls')}}"
      availability_set: "{{ item.availability_set | default(omit) }}"
      managed_disk_type: "{{ item.disk_type | default(omit) }}"
      ssh_password_enabled: no
      admin_username: 'ansible'   ###"{{ credentials.username | default('root') }}"
      ssh_public_keys:
        - path: "/home/ansible/.ssh/authorized_keys"
          key_data: "{{ credentials.sshkey }}"
      image: "{{ item.image | default(omit) }}"
      subnet_name: "{{ item.subnet_name | default(omit) }}"
      state: "{{ item.state | default(omit) }}"
    loop: "{{ azure_vms }}"
