---
- name: Create a new azure group
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  
  tasks:
  - name: Create/Update/Delete Azure Vault
    azure_rm_keyvault:
      resource_group: "{{ item.rg }}"
      vault_name: "{{ item.name }}"
      vault_tenant: "{{ item.vault_tenant }}"
      enabled_for_deployment: "{{ item.enabled_for_deployment | default(omit) }}"
      enabled_for_disk_encryption: "{{ item.enabled_for_disk_encryption | default(omit) }}"
      enabled_for_template_deployment: "{{ item.enabled_for_templates | default(omit) }}"
      sku: "{{ item.sku | default(omit) }}"
      access_policies: "{{ item.access_policies | default(omit) }}"
      state: "{{ item.state | default(omit) }}"
    loop: "{{ azure_vaults }}"
