---
- name: Create a new Azure SQL Server
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  var_files: 'vaults/sqlvault.yml'
  tasks:
  - name: Create/Update/Delete Azure SQL Server
    azure_rm_sqlserver:
      resource_group: "{{ item.rg }}"
      name: "{{ item.name }}"
      location: "{{ item.location | default(omit) }}"
      admin_username: "{{ item.credentials.username | default(omit) }}"
      admin_password: "{{ item.credentials.password | default(omit) }}"
      state: "{{ item.state | default(omit) }}"
    loop: "{{ azure_sql_servers }}"
