---
- name: Create a new azure group
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars:
  #  RG_DELETION: 'DEMO2'
  #  RG_CREATION: 'DEMO_RG'
    
  tasks:
  - Create DEMO Resource Group
    azure_rm_resourcegroup:
      name: "{{ RG_CREATION }}"
      location: 'eastus'
      tags:
        provider: 'Ansible'
        in_production: False
    when: RG_CREATION is defined
     
  - Destroy DEMO2 Resource Group
    azure_rm_resourcegroup:
      name: "{{ RG_DELETION }}"
      state: absent
      force_delete_nonempty: yes
    when: RG_DELETION is defined
