---
- name: Create a new azure group
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
#  vars:
#    RGs:
#    - name: "DEMO_RG"
#      location: "eastus"
#      tags:
#        tag1: "anothervalue"
#        tag2: "somevalue"
#    - name: "DEMO2"
#      state: "absent"
#      forcedelete: "yes"
    
  tasks:
  - name: Create/Update/Delete Azure RD
    azure_rm_resourcegroup:
      name: "{{ item.name }}"
      location: "{{ item.location | default(omit) }}"
      tags: "{{ item.tags | default(omit) }}"
      state: "{{ item.state | default('present') }}"
      force_delete_nonempty: "{{ item.forcedelete | default(omit) }}"
    loop: "{{ RGs }}"
